#!/bin/sh
set -e
LOCALE=uk_UA

case "$1" in
  remove|upgrade|deconfigure)
    add_remove_language remove $LOCALE;
    rm /usr/share/nokia-maps/html/medos/i18n/uk/ua;
    exit 0
  ;;

  failed-upgrade)
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
